//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public Education()
        {
            this.Lectures = new HashSet<Lecture>();
            this.Practical_Conducted = new HashSet<Practical_Conducted>();
            this.Seminars = new HashSet<Seminar>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<Lecture> Lectures { get; set; }
        public virtual ICollection<Practical_Conducted> Practical_Conducted { get; set; }
        public virtual ICollection<Seminar> Seminars { get; set; }
    }
}
