//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Practical_Conducted
    {
        public Practical_Conducted()
        {
            this.Practical_Booking = new HashSet<Practical_Booking>();
        }
    
        public int Id { get; set; }
        public int E_Id { get; set; }
        public string Subject { get; set; }
        public int Staff_Id { get; set; }
        public System.DateTime Date_Time { get; set; }
    
        public virtual Education Education { get; set; }
        public virtual ICollection<Practical_Booking> Practical_Booking { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
