//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int Id { get; set; }
        public int Product_Id { get; set; }
        public string Quantity { get; set; }
        public int Price { get; set; }
        public System.DateTime Date_Time { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
