//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public Staff()
        {
            this.Lectures = new HashSet<Lecture>();
            this.Practical_Conducted = new HashSet<Practical_Conducted>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public string Qualification { get; set; }
        public string Date_Of_Birth { get; set; }
        public string Picture { get; set; }
    
        public virtual ICollection<Lecture> Lectures { get; set; }
        public virtual ICollection<Practical_Conducted> Practical_Conducted { get; set; }
    }
}
